---

# the next task returns:
# - _container_storage_dir_base_local
# - _container_storage_dir_base
# - _group, _owner
# - _systemd_scope
# - _systemd_service_files_dir
# - _xdg_runtime_dir
- name: Include podman_init_vars.yml from sleif.podman
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files: sleif.podman/tasks/includes/podman_init_vars.yml
      paths: "{{ lookup('config', 'DEFAULT_ROLES_PATH') }}"

- name: Set additional facts for {{ caddy_container_name }}
  ansible.builtin.set_fact:
    _caddy_config_dir: "{{ _container_storage_dir_base_local }}/{{ caddy_container_name }}/config"
    _caddy_data_dir: "{{ _container_storage_dir_base_local }}/{{ caddy_container_name }}/data"

- name: Run tasks from {{ caddy_operation + '.yml' }}
  ansible.builtin.include_tasks:
    file: "{{ caddy_operation }}.yml"
    apply:
      tags:
        - "{{ caddy_operation }}"
  when:
    - caddy_operation in caddy_operations
  tags: "{{ caddy_operation }}"

- name: Restart caddy container {{ caddy_container_name }}  # noqa: no-changed-when
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  ansible.builtin.command: podman restart {{ caddy_container_name }}
  when: _caddy_restart_required | d(false) | bool

- name: Reload caddy configuration {{ caddy_container_name }}  # noqa: no-changed-when
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  ansible.builtin.command: podman exec -w /config {{ caddy_container_name }} caddy reload
  when:
    - not _caddy_restart_required | d(false) | bool
    - _caddy_reload_required | d(false) | bool

- name: Restart caddy frontend container if defined {{ caddy_frontend_container }}  # noqa: no-changed-when
  become: "{{ podman_rootless | bool }}"
  become_user: "{{ podman_user if podman_rootless | bool else omit }}"
  ansible.builtin.command: podman restart {{ caddy_frontend_container }}
  when:
    - _caddy_restart_required | d(false) | bool
    - caddy_frontend_container | d('') is truthy
